# Funding platforms for NSAI
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [hyperpolymath]
# ko_fi: hyperpolymath
# open_collective: hyperpolymath
# custom: ["https://hyperpolymath.dev/sponsor"]
